FROM openjdk:8-alpine as asyncprofiler
RUN apk add build-base git linux-headers
RUN git clone https://github.com/edeNFed/async-profiler.git
RUN cd async-profiler && make

FROM alpine
RUN mkdir -p /app/async-profiler/build
ADD agent /app
COPY --from=asyncprofiler /async-profiler/build /app/async-profiler/build
COPY --from=asyncprofiler /async-profiler/profiler.sh /app/async-profiler
CMD [ "/app/agent" ]

